// AUTO-GENERATED from fynd-scraper src/data/shopify_stores.py
// 110 Shopify storefronts. Do not edit by hand; re-run the converter.
import { ProductCategory } from '@pandorlabs/types';
import type { ShopifyStore } from './shopify.types';

export const SHOPIFY_STORES: ShopifyStore[] = [
  {
    id: 'tony_bianco',
    name: 'Tony Bianco',
    marketplace: 'TONY_BIANCO',
    link: 'https://tonybianco.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'heels',
          'womens-boots',
          'all-sandals',
          'womens-loafers',
          'ballet-flats',
        ],
      },
    ],
  },
  {
    id: 'castaner',
    name: 'Castaner',
    marketplace: 'CASTANER',
    link: 'https://www.castaner.com/en-us',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'cunas',
          'planas',
          'sandalias',
          'tacones',
          'botas-y-botines',
          'accesorios-mujer',
          'ultimas-tallas',
          'all',
        ],
      },
    ],
  },
  {
    id: 'piedaterre_venezia',
    name: 'Piedaterre Venezia',
    marketplace: 'PIEDATERRE_VENEZIA',
    link: 'https://piedaterrevenezia.com/en-us',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'alpaca',
          'b-r-o-d-s-k-y',
          'brodsky-1',
          'd-a-n-d-y',
          'dandy-velvet',
          'dandy-alpaca',
          'dandy-suri',
          'dandy-bevilacqua-edition',
          'dandy-linen',
          'dandy-bicolore-velluto',
          'linen',
          'm-a-r-y-j-a-n-e',
          'm-o-d-i-g-l-i-a-n-i',
          'mary-jane',
          'rubelli_seta',
          'seta',
          'bambino',
          'mary-jane-bicolore',
          'mary-jane-canvas',
          'mary-jane-dolfin',
          'mary-jane-man',
          'modigliani-velvet',
          'bevilacqua-edition',
          'modigliani-canvas',
          'cashmere',
          'modigliani-cashmere-trapuntato',
          'rubelli_velvet',
          'tuxedo',
          'modigliani-tweed',
          'modigliani-bambino-1',
          'modigliani-bicolore',
          'modigliani-bambino-pigozzi-collab',
          'modigliani-pigozzi-collab',
          'silk',
          'tuxedo-smoking',
          'tweed-1',
          'modigliani-velluto-trapuntato',
          'w-i-l-d-e',
          'wilde_velvet',
          'wilde-suri',
          'wilde-linen',
          'wilde-tuxedo',
          'velluto-alpaca',
        ],
      },
    ],
  },
  {
    id: 'carel_paris',
    name: 'Carel Paris',
    marketplace: 'CAREL_PARIS',
    link: 'https://www.carel-paris.com/en',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'babies',
          'bottines',
          'bottes',
          'slingback',
          'ballerines',
          'mocassins',
          'escarpins',
          'baskets',
          'sandales',
          'mules',
        ],
      },
      { main: ProductCategory.BAGS, handles: [] },
    ],
  },
  {
    id: 'repetto',
    name: 'Repetto',
    marketplace: 'REPETTO',
    link: 'https://repetto.com/en',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'catalogue-femme-athleisure-sweatshirts',
          'catalogue-femme-athleisure-tops-and-t-shirts',
          'brassieres',
          'catalogue-femme-athleisure-leggings',
          'cache-coeur-activewear',
          'catalogue-femme-athleisure-pantalons-and-combinaisons',
          'combinaisons-bodies',
          'catalogue-femme-athleisure-robes-and-jupes',
          'catalogue-femme-athleisure-vestes',
          'collection-enfant-activewear-1',
          'catalogue-femme-athleisure-sneakers',
          'catalogue-femme-athleisure',
        ],
      },
      {
        main: ProductCategory.SHOES,
        handles: [
          'catalogue-femme-chaussures-ballerines',
          'catalogue-femme-chaussures-babies',
          'catalogue-femme-chaussures-mocassins',
          'catalogue-femme-chaussures-bottes-and-bottines',
          'catalogue-femme-chaussures-escarpins',
          'catalogue-femme-chaussures-sandales',
          'catalogue-femme-athleisure-sneakers',
          'catalogue-femme-chaussures',
        ],
      },
      {
        main: ProductCategory.BAGS,
        handles: [
          'sac-gala',
          'sac-opera',
          'sac-plume',
          'catalogue-femme-maroquinerie',
        ],
      },
    ],
  },
  {
    id: 'andrea_gomez',
    name: 'Andrea Gomez',
    marketplace: 'ANDREA_GOMEZ',
    link: 'https://andrea-gomez.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'flats',
          'oxfords',
          'ballerinas',
          'loafers',
          'mules',
          'sandals',
          'platforms',
          'slingbacks',
          'boots',
          'sneakers',
        ],
      },
    ],
  },
  {
    id: 'dear_frances',
    name: 'Dear Frances',
    marketplace: 'DEAR_FRANCES',
    link: 'https://dearfrances.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['flats', 'loafers', 'sandals', 'boots', 'pumps', 'trainers'],
      },
    ],
  },
  {
    id: 'loeffler_randall',
    name: 'Loeffler Randall',
    marketplace: 'LOEFFLER_RANDALL',
    link: 'https://loefflerrandall.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'flats',
          'flat-sandals',
          'heeled-sandals',
          'espadrilles',
          'pumps-mules',
          'footwear',
        ],
      },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'dresses',
          'tops',
          'bottoms',
          'sweaters-knits',
          'outerwear',
          'apparel',
        ],
      },
      {
        main: ProductCategory.BAGS,
        handles: [
          'totes',
          'clutches',
          'crossbody',
          'shoulder-bags',
          'event-handbags',
          'handbags',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'jewelry',
          'belts',
          'hats',
          'hair-accessories',
          'soft-accessories',
          'accessories',
        ],
      },
    ],
  },
  {
    id: 'mama_praia',
    name: 'Mama Praia',
    marketplace: 'MAMA_PRAIA',
    link: 'https://mamapraia.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'fisherman-sandals',
          'leather-sandals-for-women-mules',
          'toe-sandals',
          'ankle-sandals',
        ],
      },
    ],
  },
  {
    id: 'aemery',
    name: 'Aemery',
    marketplace: 'AEMERY',
    link: 'https://aemery.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['sandals', 'heels', 'flats', 'boots', 'footwear'],
      },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'coats-jackets',
          'dresses',
          'knitwear',
          'shirts-tops',
          'skirts-shorts',
          'trousers',
          'apparel',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
    ],
  },
  {
    id: 'lachoix',
    name: 'Lachoix',
    marketplace: 'LACHOIX',
    link: 'https://www.lachoix.com/en-us',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'lachoix-collection-loafers',
          'lachoix-collection-penny-loafers',
          'ballerinas',
          'lachoix-collection-double-straps-sandals',
          'slingback',
          'lachoix-collection-slippers',
        ],
      },
    ],
  },
  {
    id: 'anne_thomas',
    name: 'Anne Thomas',
    marketplace: 'ANNE_THOMAS',
    link: 'https://www.us.annethomas.fr',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['chaussures', 'boots', 'sandales'],
      },
    ],
  },
  {
    id: 'hereu',
    name: 'Hereu',
    marketplace: 'HEREU',
    link: 'https://hereustudio.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'sandals-shoes',
          'soft-shoes',
          'loafer-shoes',
          'heeled-shoes',
          'boots-shoes',
        ],
      },
      {
        main: ProductCategory.BAGS,
        handles: [
          'crossbody-bags',
          'shoulder-bags',
          'tote-bags',
          'mini-bags',
          'basket-bags',
          'small-leather-goods',
        ],
      },
    ],
  },
  {
    id: 'augusta',
    name: 'Augusta',
    marketplace: 'AUGUSTA',
    link: 'https://augustathebrand.com/en-us',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'mary-janes',
          'patent-leather-mary-janes',
          'metallic-leather-mary-janes-for-women',
          'soft-leather-mary-janes-for-women',
          'suede-mary-janes-for-women',
          'calf-hair-mary-janes-for-women',
          'velvet-mary-janes-for-women',
          'mary-janes',
          'ballet-flats',
          'loafers',
          'sandals',
          'heels',
          'boots',
        ],
      },
    ],
  },
  {
    id: 'yuni_buffa',
    name: 'Yuni Buffa',
    marketplace: 'YUNI_BUFFA',
    link: 'https://yunibuffa.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['flats', 'loafers', 'heels', 'sandals'],
      },
    ],
  },
  {
    id: 'souliers_martinez',
    name: 'Souliers Martinez',
    marketplace: 'SOULIERS_MARTINEZ',
    link: 'https://souliers-martinez.com/en-us',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'woven-new-in-styles',
          'mesh-1',
          'designer-flats',
          'designer-sandals',
          'designer-pumps',
          'designer-platforms',
          'designer-boots',
          'iconic-styles',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
    ],
  },
  {
    id: 'ancient_greek_sandals',
    name: 'Ancient Greek Sandals',
    marketplace: 'ANCIENT_GREEK_SANDALS',
    link: 'https://www.ancient-greek-sandals.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'ankle-strap',
          'back-strap-sandals',
          'ballet-flats',
          'womens-sandals-clogs',
          'closed-toe',
          'womens-sandals-comfort-soles',
          'fisherman',
          'flip-flops',
          'gladiators',
          'heels',
          'lace-up-styles',
          'mary-jane',
          'slides',
          'slippers',
          'sling-backs',
          'toe-ring-sandals',
          'thongs',
        ],
      },
    ],
  },
  {
    id: 'st_agni',
    name: 'St Agni',
    marketplace: 'ST_AGNI',
    link: 'https://www.st-agni.com',
    collections: [
      { main: ProductCategory.SHOES, handles: ['footwear'] },
      { main: ProductCategory.BAGS, handles: ['bags'] },
      {
        main: ProductCategory.CLOTHING,
        handles: ['dresses', 'leather-ready-to-wear', 'the-suede-edit'],
      },
    ],
  },
  {
    id: 'mapache',
    name: 'Mapache',
    marketplace: 'MAPACHE',
    link: 'https://www.mapache.shop',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['huaraches-femme', 'sandales-femme', 'oaxaca'],
      },
    ],
  },
  {
    id: 'sr_13_09',
    name: 'Sr 13 09',
    marketplace: 'SR_13_09',
    link: 'https://1309sr.com/en-us',
    collections: [
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.BAGS, handles: ['sacs'] },
    ],
  },
  {
    id: 'flattered',
    name: 'Flattered',
    marketplace: 'FLATTERED',
    link: 'https://us.flattered.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'boots',
          'ballet-flats',
          'indoor',
          'high-shaft-boots',
          'heels',
          'heeled-sandals',
          'loafers',
          'sandals',
          'sneakers',
        ],
      },
      {
        main: ProductCategory.BAGS,
        handles: [
          'crosshoulder-bag',
          'clutch-bags',
          'shoulder-bags',
          'tote-bags',
          'top-handle-bags',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories', 'belts'] },
    ],
  },
  {
    id: 'milaner',
    name: 'Milaner',
    marketplace: 'MILANER',
    link: 'https://bymilaner.com',
    collections: [
      { main: ProductCategory.SHOES, handles: ['flats', 'sandals', 'heels'] },
      {
        main: ProductCategory.BAGS,
        handles: [
          'totes',
          'hobo-bags',
          'cross-body',
          'mini-bags',
          'clutches',
          'backpacks',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['hats', 'scarves', 'sunglasses', 'straps'],
      },
    ],
  },
  {
    id: 'flowze',
    name: 'Flowze',
    marketplace: 'FLOWZE',
    link: 'https://flowze.it/en',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['f-l-o', 'f-l-o-s-l-i-d-e', 'f-l-o-t-w-i-n'],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['braccialetto', 'portachiavi', 'charm-bag', 'borsa'],
      },
    ],
  },
  {
    id: 'yuko_imanishi_plus',
    name: 'Yuko Imanishi Plus',
    marketplace: 'YUKO_IMANISHI_PLUS',
    link: 'https://yukoimanishi-plus.com/en',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['standard-item', 'pumps', 'sandal', 'sneaker', 'boots'],
      },
    ],
  },
  {
    id: 'bembien',
    name: 'Bembien',
    marketplace: 'BEMBIEN',
    link: 'https://bembien.com',
    collections: [
      { main: ProductCategory.SHOES, handles: ['sandals', 'mules', 'shoes'] },
      {
        main: ProductCategory.BAGS,
        handles: [
          'handbags-tote',
          'handbags-shoulder',
          'handbags-crossbody',
          'handbags-bucket',
          'handbags-clutchmini',
        ],
      },
    ],
  },
  {
    id: 'superga',
    name: 'Superga',
    marketplace: 'SUPERGA',
    link: 'https://www.superga-usa.com',
    collections: [{ main: ProductCategory.SHOES, handles: ['women'] }],
  },
  {
    id: 'staud',
    name: 'Staud',
    marketplace: 'STAUD',
    link: 'https://staud.clothing',
    collections: [
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.BAGS, handles: ['bags-accessories'] },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
      { main: ProductCategory.CLOTHING, handles: ['clothing-all'] },
    ],
  },
  {
    id: 'mansur_gavriel',
    name: 'Mansur Gavriel',
    marketplace: 'MANSUR_GAVRIEL',
    link: 'https://www.mansurgavriel.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['ballerina-flats', 'sandals', 'heels'],
      },
      {
        main: ProductCategory.BAGS,
        handles: [
          'tote',
          'crossbody-bags',
          'mini-bag',
          'shoulder-bags',
          'clutches',
          'sale-bags-1',
          'bonbon-bag',
          'everyday-cabas',
          'candy-bag',
          'cloud-clutches',
          'gaia-shoulder-bag',
          'hera-bag',
          'icons',
          'lady-bag',
        ],
      },
    ],
  },
  {
    id: 'manu_atelier',
    name: 'Manu Atelier',
    marketplace: 'MANU_ATELIER',
    link: 'https://manuatelier.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'manu-ballet-flats',
          'almond-toe-sandals-shoes',
          'sandals',
          'loafers',
          'boots',
        ],
      },
      {
        main: ProductCategory.BAGS,
        handles: [
          'le-cambon',
          'tote-du-jour',
          'mini-tote-du-jour',
          'cylinder',
          'xx-mini-cylinder',
          'gala',
          'mini-gala',
          'crossbody',
          'shoulder',
          'tote',
        ],
      },
    ],
  },
  {
    id: 'naguisa',
    name: 'Naguisa',
    marketplace: 'NAGUISA',
    link: 'https://naguisa.com/en',
    collections: [{ main: ProductCategory.SHOES, handles: ['all'] }],
  },
  {
    id: 'spelta_milano',
    name: 'Spelta Milano',
    marketplace: 'SPELTA_MILANO',
    link: 'https://www.speltamilano.it/en',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'ballerine',
          'stringate',
          'slippers',
          'mocassini',
          'specials',
        ],
      },
    ],
  },
  {
    id: 'steve_madden',
    name: 'Steve Madden',
    marketplace: 'STEVE_MADDEN',
    link: 'https://www.stevemadden.com/',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: [
          'womens-sandals',
          'womens-heels',
          'womens-sneakers',
          'womens-boots',
          'womens-booties',
          'loafers-flats',
          'womens-platforms',
          'womens-wedges',
          'trends-slides',
          'trends-mules',
          'wide-and-extended-sizes',
          'boots-booties',
        ],
      },
    ],
  },
  {
    id: 'farm_rio',
    name: 'Farm Rio',
    marketplace: 'FARM_RIO',
    link: 'https://farmrio.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['boots-sneakers', 'loafers-mules', 'shoes-sandals', 'shoes'],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'maxi-dresses',
          'midi-dresses',
          'short-dresses',
          'tops',
          't-shirt',
          'blouses',
          'bodysuits',
          'rompers-and-jumpsuits',
          'jumpsuits',
          'rompers',
          'bottoms',
          'skirts',
          'pants',
          'shorts',
          'outerwear',
          'puffer-jackets',
          'blazers',
          'sweaters-knits',
          'cardigans',
          'swimwear',
          'bikinis',
          'one-piece-swimsuits',
          'sarongs',
          'cover-ups',
        ],
      },
    ],
  },
  {
    id: 'attersee',
    name: 'Attersee',
    marketplace: 'ATTERSEE',
    link: 'https://shopattersee.com/',
    collections: [
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.BAGS, handles: ['bags'] },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'knitwear',
          'shirts-and-tops',
          'pants',
          'jackets',
          'vests',
          'skirts',
          'the-occasion-edit',
          'dresses',
          'coats-jackets',
          'scarves-and-wraps',
          'summer-sale',
          'the-resort-collection',
          'the-core-collection',
        ],
      },
    ],
  },
  {
    id: 'the_sandal_company',
    name: 'The Sandal Company',
    marketplace: 'THE_SANDAL_COMPANY',
    link: 'https://www.the-sandal-company.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'shirts',
          'essentials',
          'dresses',
          'knitwear',
          'pants',
          'jackets',
          'tailoring',
          'denim',
          'clothing-view-all',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.BAGS, handles: ['handbags'] },
    ],
  },
  {
    id: 'matteau',
    name: 'Matteau',
    marketplace: 'MATTEAU',
    link: 'https://int.matteau-store.com/',
    collections: [
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['belts', 'matteau-stripe-towel-black-ecru', 'accessories'],
      },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'shirts',
          'essentials',
          'dresses',
          'knitwear',
          'pants',
          'jackets',
          'tailoring',
          'denim',
          'tops',
          'briefs',
          'maillots',
          'swimwear',
          'clothing-view-all',
        ],
      },
    ],
  },
  {
    id: 'deiji_studios',
    name: 'Deiji Studios',
    marketplace: 'DEIJI_STUDIOS',
    link: 'https://us.deijistudios.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'tops',
          'bottoms',
          'dresses-1',
          'lounge-sets',
          'outerwear',
          'jersey-seperates',
          'shop-all',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories-1'] },
    ],
  },
  {
    id: 'pixie_market',
    name: 'Pixie Market',
    marketplace: 'PIXIE_MARKET',
    link: 'https://www.pixiemarket.com/',
    collections: [
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'tops',
          'sweaters-knits',
          'shirts-blouses',
          'long-sleeve',
          'short-sleeves',
          'tees-tanks',
          'sweatshirts',
          'dresses',
          'casual-dresses',
          'mini-dresses',
          'midi-maxi-dresses',
          'bottoms',
          'skirts',
          'pants',
          'shorts',
          'jumpsuits',
          'outerwear',
          'clothing-jackets-coats',
          'clothing-jackets-blazers',
          'pixie-market',
          'back-to-stock',
          'whats-new',
        ],
      },
    ],
  },
  {
    id: 'the_frankie_shop',
    name: 'The Frankie Shop',
    marketplace: 'THE_FRANKIE_SHOP',
    link: 'https://thefrankieshop.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'womens-outerwear',
          'womens-tops',
          'womens-bottoms',
          'womens-dresses',
          'womens-jumpsuits',
          'womens-knitwear',
          'womens-loungewear',
          'womens-swimwear',
          'womens-suits',
          'womens-denim-clothing',
          'womens-the-essentials',
          'womens-new-arrivals',
          'womens-clothing',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['womens-shoes'] },
      { main: ProductCategory.ACCESSORIES, handles: ['womens-accessories'] },
    ],
  },
  {
    id: 'beaufille',
    name: 'Beaufille',
    marketplace: 'BEAUFILLE',
    link: 'https://beaufille.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: ['tops', 'bottoms', 'dresses'],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.JEWELRY, handles: ['jewelry'] },
    ],
  },
  {
    id: 'vrggrl',
    name: 'Vrggrl',
    marketplace: 'VRGGRL',
    link: 'https://www.vrggrl.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'dresses',
          'mini-dresses',
          'midi-maxi-dresses',
          'tops',
          'sleeveless-tops',
          'short-sleeve-tops',
          'long-sleeve-tops',
          'shirts',
          'vests',
          'tees',
          'bottoms',
          'pants',
          'skirts',
          'shorts',
          'skorts',
          'denim-edit',
          'jeans',
          'sets',
          'outerwear',
          'jumpers-sweaters',
          'cardigans',
          'jackets-coats',
          'blazers',
          'clothing',
          'most-loved',
          'summer-edit',
          'winter-edit',
          'wedding-guest-edit',
          'denim-edit',
          'linen-edit',
          'the-print-edit',
          'sale',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
    ],
  },
  {
    id: 'soeur',
    name: 'Soeur',
    marketplace: 'SOEUR',
    link: 'https://us.soeur.fr',
    collections: [
      { main: ProductCategory.SHOES, handles: ['chaussures'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'petites-maroquinerie',
          'chapeaux',
          'foulards',
          'gants-bonnets',
          'chaussettes',
          'ceintures-createur-femme',
          'eyewear',
          'accessoires-voir-tout',
        ],
      },
      { main: ProductCategory.JEWELRY, handles: ['bijoux'] },
      {
        main: ProductCategory.BAGS,
        handles: [
          'sacs-en-bandoulieres-femme',
          'sacs-seau',
          'sacs-cabas',
          'sacs-maxi',
          'sacs-mini',
          'petites-maroquinerie',
          'tote-bags',
          'sacs-bellissima',
          'sacs-cheri',
          'sacs-nouveautes',
          'winona',
          'saudade',
          'suzette',
          'uma',
          'cosima',
        ],
      },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'robes',
          'tops',
          'chemises',
          't-shirts-sweatshirts',
          'jupes-shorts',
          'pantalons',
          'denim',
          'cardigans',
          'pulls',
          'vestes',
          'manteaux',
          'les-ensembles',
          'lido-e25-maillots-de-bain',
          'voir-tout-pret-a-porter',
          'les-essentiels',
        ],
      },
    ],
  },
  {
    id: 'dissh',
    name: 'Dissh',
    marketplace: 'DISSH',
    link: 'https://dissh.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'dresses',
          'tops',
          'skirts',
          'skorts',
          'pants',
          'knitwear',
          'sets',
          'denim',
          'shorts',
          'blazers',
          'sweaters',
          'jackets-coats',
          'swimwear',
          'all-clothing',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['belts', 'gifting', 'sunglasses', 'accessories'],
      },
      { main: ProductCategory.BAGS, handles: ['bags'] },
      { main: ProductCategory.JEWELRY, handles: ['jewellery'] },
    ],
  },
  {
    id: 'rue_sophie',
    name: 'Rue Sophie',
    marketplace: 'RUE_SOPHIE',
    link: 'https://ruesophie.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'women-tops',
          'bottoms',
          'dresses-minimalist',
          'jackets-coats',
        ],
      },
    ],
  },
  {
    id: 'victoria_leivissa',
    name: 'Victoria Leivissa',
    marketplace: 'VICTORIA_LEIVISSA',
    link: 'https://victoria.leivissa.com/en-us/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'blouse-crop-ss25',
          'dresses-ss25-1',
          'pareo-skirt-ss25',
          'trousers-ss25',
          'sets-ss25',
        ],
      },
      { main: ProductCategory.BAGS, handles: ['bag-ss25'] },
      {
        main: ProductCategory.JEWELRY,
        handles: [
          'pendant',
          'sari',
          'chains',
          'the-rings',
          'the-bracelets',
          'earrings',
          'all',
        ],
      },
    ],
  },
  {
    id: 'celia_b',
    name: 'Celia B',
    marketplace: 'CELIA_B',
    link: 'https://celiab.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'dresses',
          'skirts',
          'tops',
          'pants',
          'crochet',
          'coats-jackets',
          'knitwear-sweaters',
          'swimwear',
        ],
      },
    ],
  },
  {
    id: 'la_veste',
    name: 'La Veste',
    marketplace: 'LA_VESTE',
    link: 'https://lavestelaveste.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'all-meri',
          'icons',
          'towel-clothing',
          'blazers-winter',
          'shirts-winter',
          'vests-winter',
          't-shirts-1',
          'pants-winter',
          'shorts-summer-1',
          'skirts-winter',
          'jumpsuits-winter',
          'dresses-winter',
          'blazers-fw25',
          'shirts-fw25',
          'coats-fw25',
          'pants-fw25',
          'skirts-fw25',
          'jumpsuits-fw25',
          'dresses-fw25',
          'all-fw25',
          'new',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.BAGS, handles: ['bags'] },
      { main: ProductCategory.ACCESSORIES, handles: ['belts-1', 'hats-1'] },
    ],
  },
  {
    id: 'manoush',
    name: 'Manoush',
    marketplace: 'MANOUSH',
    link: 'https://manoush.com/en/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'robes',
          'tops-chemises-1',
          'jupes-shorts',
          'pantalons-jeans-1',
          'veste-manteaux',
          'mailles-sweats-1',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['chaussures'] },
    ],
  },
  {
    id: 'alemais',
    name: 'Alemais',
    marketplace: 'ALEMAIS',
    link: 'https://alemais.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'dresses',
          'tops',
          'trousers-shorts',
          'skirts',
          'denim',
          'knitwear',
          'jackets-coats',
          'sets',
          'swim',
          'sale',
          'rent',
          'new-arrivals',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
      { main: ProductCategory.SHOES, handles: ['shoes'] },
    ],
  },
  {
    id: 'doen',
    name: 'Doen',
    marketplace: 'DOEN',
    link: 'https://www.shopdoen.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'dresses',
          'tops',
          'knitwear',
          'skirts',
          'tees',
          'pants-shorts',
          'denim',
          'outerwear',
          'delicates',
          'sleepwear',
          'slips',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['accessories', 'favorite-characters'],
      },
      { main: ProductCategory.SHOES, handles: ['footwear'] },
      { main: ProductCategory.BAGS, handles: ['bags-pouches'] },
    ],
  },
  {
    id: 'kujten',
    name: 'Kujten',
    marketplace: 'KUJTEN',
    link: 'https://www.kujten.com/en-us',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'pulls-sweats-femme',
          'gilets-cardigans-cachemire-femme',
          'capes-ponchos-cachemire-femme',
          'vestes-manteaux-cachemire-femme',
          'tops-t-shirts-femme',
          'robes-jupes',
          'pantalons-shorts-cachemire-femme',
          'chemises-femme',
          'jeans-femme',
          'le-bain-femme',
          'pret-a-porter-cachemire-femme',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'bandanas-cachemire',
          'echarpes-cachemire',
          'cols-tours-de-cou-cachemire',
          'bonnets-cagoules-cachemire',
          'gants-mitaines-cachemire',
          'chaussettes-guetres-cachemire',
          'ceintures',
          'parfum',
          'accessoires',
        ],
      },
      { main: ProductCategory.BAGS, handles: ['sacs-cachemire'] },
    ],
  },
  {
    id: 'eric_bompard',
    name: 'Eric Bompard',
    marketplace: 'ERIC_BOMPARD',
    link: 'https://www.eric-bompard.com/en-us',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'pulls-femme',
          'gilets-et-cardigans-femme',
          'manteaux-femme',
          'tops',
          't-shirts',
          'chemises-femme',
          'robes-et-jupes',
          'pantalons-femme',
          'twin-sets-femme',
          'ponchos',
          'beachwear',
          'pulls-femme',
          'pulls-col-rond-femme',
          'pulls-v-femme',
          'pulls-col-montant-femme',
          'pulls-cols-roule-femme',
          'pulls-a-capuche-femme',
          'pret-a-porter-femme',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'carres-femme',
          'etoles-femme',
          'echarpes-femme',
          'ponchos',
          'cols-et-tours-de-cou-femme',
          'bonnets-femme',
          'gants-et-mitaines-cachemire-femme',
          'chaussettes-femme',
          'ceintures-femme',
          'accessoires-femme',
        ],
      },
    ],
  },
  {
    id: 'pinotti',
    name: 'Pinotti',
    marketplace: 'PINOTTI',
    link: 'https://pinotticashmere.com/en',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: ['maglieria', 'collezione-cashmere'],
      },
      { main: ProductCategory.BAGS, handles: ['borse'] },
      { main: ProductCategory.ACCESSORIES, handles: ['accessori'] },
    ],
  },
  {
    id: 'self_portrait',
    name: 'Self Portrait',
    marketplace: 'SELF_PORTRAIT',
    link: 'https://us.self-portrait.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'new-arrivals',
          'new-arrivals-dresses',
          'new-arrivals-knitwear',
          'new-arrivals-tops',
          'new-arrivals-bottoms',
          'new-arrivals-outerwear',
          'new-arrivals-denim',
          'swimwear',
          'ready-to-wear',
          'dresses',
          'knitwear',
          'matching-sets',
          'tops',
          'bottoms',
          'outerwear',
          'denim',
          'jumpsuits',
          'swimwear',
          'exclusives',
          'icons',
          'modest-edit',
          'jewellery',
          'wedding',
          'wedding-guests',
          'bridesmaids',
          'modest-edit',
          'party-edit',
          'corp-core',
          'summer-occasions',
          'christopher-kane-residency',
          'new-worlds-with-jisoo',
        ],
      },
      { main: ProductCategory.JEWELRY, handles: ['jewellery'] },
      { main: ProductCategory.BAGS, handles: ['handbags'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['wedding-accessories', 'flower-girls'],
      },
    ],
  },
  {
    id: 'tresse_paris',
    name: 'Tresse Paris',
    marketplace: 'TRESSE_PARIS',
    link: 'https://tresse-paris.com/en-us',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'robes',
          'jeans-1',
          'chemises-tops',
          'maille',
          'pantalons-shorts',
          'tee-shirts',
          'nos-ensembles-en-soie-1',
          'vestes',
          'valise-de-l-argentine',
          'ventes-privileges',
          'maillots-de-bain',
          'ventes-privileges',
          'beach-capsule-pe25',
          'nos-pieces-ceremonie',
          'selection-tresse',
          'nos-intemporels',
          'valise-de-l-argentine',
          'ventes-privileges',
          'valise-de-la-grece',
          'jeans-1',
        ],
      },
      { main: ProductCategory.JEWELRY, handles: ['bijoux'] },
      { main: ProductCategory.BAGS, handles: ['sacs'] },
      { main: ProductCategory.SHOES, handles: ['souliers'] },
      { main: ProductCategory.ACCESSORIES, handles: ['accessoires-1'] },
    ],
  },
  {
    id: 'stella_and_suzie',
    name: 'Stella And Suzie',
    marketplace: 'STELLA_AND_SUZIE',
    link: 'https://stellaetsuzie.com/en-us',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'robes',
          'blouses-chemises',
          'bas-combinaisons',
          'denim',
          'mailles-sweats',
          'vestes-manteaux',
          'maroquinerie',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessoires'] },
    ],
  },
  {
    id: 'donni',
    name: 'Donni',
    marketplace: 'DONNI',
    link: 'https://shopdonni.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: ['tops', 'bottoms', 'shorts', 'sweaters-1'],
      },
      { main: ProductCategory.JEWELRY, handles: ['jewelry'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['scrunchies', 'accessories-1'],
      },
    ],
  },
  {
    id: 'leset',
    name: 'Leset',
    marketplace: 'LESET',
    link: 'https://leset.com/',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['the-mules', 'the-louis', 'shoes'],
      },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'tops',
          'pants-1',
          't-shirts',
          'tank-tops',
          'dresses',
          'sweaters-1',
          'cardigans-1',
          'skirts-shorts',
          'outerwear',
          'underthings',
          'all',
        ],
      },
    ],
  },
  {
    id: 'cami_nyc',
    name: 'Cami Nyc',
    marketplace: 'CAMI_NYC',
    link: 'https://www.caminyc.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'camis',
          'cami-dresses',
          'bodysuits',
          'blouses-1',
          'bottoms',
          'jackets-blazers',
          'undergarments',
          'all',
        ],
      },
    ],
  },
  {
    id: 'petite_plume',
    name: 'Petite Plume',
    marketplace: 'PETITE_PLUME',
    link: 'https://www.petite-plume.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'womens-pajamas',
          'women-short-sets',
          'womens-nightgowns',
          'womens-robes',
          'womens-loungewear',
          'womens-collection',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['womens-accessories'] },
    ],
  },
  {
    id: 'eberjey',
    name: 'Eberjey',
    marketplace: 'EBERJEY',
    link: 'https://eberjey.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'the-wedding-shop-bride',
          'bundles',
          'women-lingerie',
          'women-lounge',
          'womens-pajamas',
          'robes',
          'the-travel-shop',
          'sale',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
    ],
  },
  {
    id: 'malfroy',
    name: 'Malfroy',
    marketplace: 'MALFROY',
    link: 'https://www.shop.malfroy.com/en-us',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'carres-en-coton-et-soie',
          'carres-en-laine-et-soie',
          'carres-de-soie',
        ],
      },
      { main: ProductCategory.JEWELRY, handles: ['bijoux'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'echarpes-en-laine-et-soie',
          'echarpes-en-coton-et-soie',
          'echarpes-en-lin-et-coton',
          'echarpes-en-soie',
          'echarpes',
          'bandeaux',
          'bracelets-dores-et-soie',
          'bracelets-cuir-et-soie',
        ],
      },
    ],
  },
  {
    id: 'loulou_de_saison',
    name: 'Loulou De Saison',
    marketplace: 'LOULOU_DE_SAISON',
    link: 'https://www.louloudesaison.com/en-us',
    collections: [
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.BAGS, handles: ['bags'] },
      { main: ProductCategory.ACCESSORIES, handles: ['accessoires'] },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'coats-jackets',
          'knits-sweaters',
          'pants-shorts',
          'top',
          'dresses',
          'swimwear',
          'all',
        ],
      },
    ],
  },
  {
    id: 'co',
    name: 'Co',
    marketplace: 'CO',
    link: 'https://co-collections.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'essentials',
          'dresses-skirts',
          'knitwear',
          'jackets-coats',
          'shirts',
          'pants',
          'tailoring-suiting',
          'denim',
          'clothing-view-all',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.BAGS, handles: ['bags'] },
    ],
  },
  {
    id: 'belle_anna',
    name: 'Belle Anna',
    marketplace: 'BELLE_ANNA',
    link: 'https://www.belle-anna.com/',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'tops',
          'pants-shorts',
          'skirts',
          'dresses',
          'swim',
          'new-arrivals',
          'all',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
    ],
  },
  {
    id: 'frejanyc',
    name: 'Frejanyc',
    marketplace: 'FREJANYC',
    link: 'https://frejanyc.com',
    collections: [
      { main: ProductCategory.BAGS, handles: ['totes', 'shoulder-bags'] },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
    ],
  },
  {
    id: 'laurencebras',
    name: 'Laurencebras',
    marketplace: 'LAURENCEBRAS',
    link: 'https://laurencebras.com/en',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'chemises',
          'mailles',
          'pantalons',
          'jupes',
          'robes',
          'vestes-et-manteaux',
          'le-denim',
          'le-cuir',
          'vetements',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['chaussures'] },
      { main: ProductCategory.BAGS, handles: ['sacs'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['ceintures', 'bijoux', 'foulard', 'accessoires'],
      },
    ],
  },
  {
    id: 'sourceunknown',
    name: 'Sourceunknown',
    marketplace: 'SOURCEUNKNOWN',
    link: 'https://sourceunknown.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'outerwear',
          'knitwear',
          'dresses-jumpsuits',
          'tops-shirts',
          'trousers-shorts',
          'denim-collection',
          'skirts',
          'co-ord-set',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.BAGS, handles: ['bags'] },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories', 'belts'] },
    ],
  },
  {
    id: 'dragondiffusion',
    name: 'Dragondiffusion',
    marketplace: 'DRAGONDIFFUSION',
    link: 'https://dragondiffusion.com',
    collections: [
      { main: ProductCategory.BAGS, handles: ['all-bags'] },
      { main: ProductCategory.ACCESSORIES, handles: ['belts'] },
    ],
  },
  {
    id: 'polene_paris',
    name: 'Polene Paris',
    marketplace: 'POLENE_PARIS',
    link: 'https://eng.polene-paris.com',
    collections: [
      { main: ProductCategory.BAGS, handles: ['handbags'] },
      { main: ProductCategory.JEWELRY, handles: ['jewellery'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'small-leather-goods',
          'interior-decorations',
          'in-upcycled-leather',
        ],
      },
    ],
  },
  {
    id: 'liffner',
    name: 'Liffner',
    marketplace: 'LIFFNER',
    link: 'https://liffner.co',
    collections: [
      {
        main: ProductCategory.BAGS,
        handles: [
          'all-bags',
          'new-arrivals',
          'sale',
          'coming-soon',
          'bestsellers',
          'bucket-bags',
          'shoulder-bags',
          'small-bags',
          'tote-bags',
          'baskets',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'all-accessories',
          'bag-charms',
          'belts',
          'bracelets',
          'earrings',
          'rings',
        ],
      },
    ],
  },
  {
    id: 'leoetviolette',
    name: 'Leoetviolette',
    marketplace: 'LEOETVIOLETTE',
    link: 'https://www.leoetviolette.com/en-us',
    collections: [
      { main: ProductCategory.BAGS, handles: ['femme'] },
      { main: ProductCategory.ACCESSORIES, handles: ['petite-maroquinerie'] },
    ],
  },
  {
    id: 'hunting_season',
    name: 'Hunting Season',
    marketplace: 'HUNTING_SEASON',
    link: 'https://hunting-season.com',
    collections: [
      {
        main: ProductCategory.BAGS,
        handles: [
          'holiday-pre-orderr',
          'the-leopard-collection',
          'jewelry',
          'the-small-leather-goods',
          'gift-sets',
          'evening-bags',
          'raffia-baskets',
          'small-leather-goods',
          'totes-top-handles',
          'small-mini-bags',
          'cross-body-bags',
          'travel-bags',
          'sale',
        ],
      },
      { main: ProductCategory.JEWELRY, handles: ['jewelry'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['the-small-leather-goods', 'gift-sets'],
      },
    ],
  },
  {
    id: 'aestherekme',
    name: 'Aestherekme',
    marketplace: 'AESTHEREKME',
    link: 'https://aestherekme.com',
    collections: [{ main: ProductCategory.BAGS, handles: ['all'] }],
  },
  {
    id: 'yuzefi',
    name: 'Yuzefi',
    marketplace: 'YUZEFI',
    link: 'https://yuzefi.com',
    collections: [
      {
        main: ProductCategory.BAGS,
        handles: [
          'new-in',
          'pre-order',
          'xl-mochi',
          'brioche',
          'oyster-mini-shoulder-bag',
          'icons',
          'autumn-hues',
          'embossed-leathers',
          'woven-edit',
          'bestsellers',
          'back-in-stock',
          'the-mochi-series',
          'gyoza',
          'oyster-series',
          'pretzels',
          'fortune-cookie',
          'tote-bags',
          'shoulder-bags',
          'crossbody-bags',
          'clutchesandpouches',
          'top-handle',
          'mini-bag',
        ],
      },
      { main: ProductCategory.CLOTHING, handles: ['ready-to-wear'] },
    ],
  },
  {
    id: 'ateliersauguste',
    name: 'Ateliersauguste',
    marketplace: 'ATELIERSAUGUSTE',
    link: 'https://en.ateliersauguste.com',
    collections: [
      {
        main: ProductCategory.BAGS,
        handles: [
          'newin',
          'sacs-mini',
          'sacs-en-bandouliere',
          'sacs-porte-epaule',
          'sacs-porte-main',
          'sacs-femme',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'petite-maroquinerie',
          'portefeuilles',
          'porte-cartes',
          'portefeuilles-zippes',
        ],
      },
    ],
  },
  {
    id: 'cordera',
    name: 'Cordera',
    marketplace: 'CORDERA',
    link: 'https://cordera.es',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'fw25',
          'outerwear-fw25',
          'knitwear-fw25',
          'shirts-fw25',
          'bottoms-fw25',
          'pre-fall-25',
          'outerwear-pre-fall-25',
          'knitwear-pre-fall-25',
          'dresses-pre-fall-25',
          'shirts-pre-fall-25',
          'tops-pre-fall-25',
          'bottoms-pre-fall-25',
        ],
      },
      {
        main: ProductCategory.SHOES,
        handles: ['shoes-fw25', 'shoes-pre-fall-25'],
      },
      {
        main: ProductCategory.BAGS,
        handles: ['bags-fw25', 'bags-pre-fall-25'],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['accessories-fw25', 'accessories-pre-fall-25'],
      },
    ],
  },
  {
    id: 'destree',
    name: 'Destree',
    marketplace: 'DESTREE',
    link: 'https://destree.com/en-us',
    collections: [
      { main: ProductCategory.BAGS, handles: ['all-bags'] },
      { main: ProductCategory.JEWELRY, handles: ['jewelry'] },
      { main: ProductCategory.ACCESSORIES, handles: ['all-accessories'] },
      { main: ProductCategory.CLOTHING, handles: ['all-ready-to-wear'] },
    ],
  },
  {
    id: 'heimat_atlantica',
    name: 'Heimat Atlantica',
    marketplace: 'HEIMAT_ATLANTICA',
    link: 'https://heimat-atlantica.com',
    collections: [
      {
        main: ProductCategory.BAGS,
        handles: [
          'camarinas-bobbin-lace-fw25',
          'shella-collection',
          'basket-bags',
          'the-grand-tour-fw25',
          'lares-collection',
          'pouches',
          'cupid-bags',
          'custom-made',
        ],
      },
      { main: ProductCategory.JEWELRY, handles: ['jewelry'] },
    ],
  },
  {
    id: 'elenimalami',
    name: 'Elenimalami',
    marketplace: 'ELENIMALAMI',
    link: 'https://www.elenimalami.com',
    collections: [
      { main: ProductCategory.BAGS, handles: ['handbags'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['silk-scarves', 'cushions'],
      },
    ],
  },
  {
    id: 'shrimps',
    name: 'Shrimps',
    marketplace: 'SHRIMPS',
    link: 'https://shrimps.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'new-in',
          'coats-jackets',
          'knitwear',
          'dresses',
          'tops',
          'bottom',
          'loungewear',
          'occasionwear',
          'shrimps-baby-and-kidswear',
        ],
      },
      { main: ProductCategory.BAGS, handles: ['bags', 'bridal-bags'] },
      {
        main: ProductCategory.JEWELRY,
        handles: ['jewellery', 'bridal-jewellery-accessories'],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'shrimps-rental',
          'shrimps-icons',
          'hats-scarves',
          'shrimps-homeware',
          'bridal-gifts',
          'gifts',
        ],
      },
    ],
  },
  {
    id: 'imemoi',
    name: 'Imemoi',
    marketplace: 'IMEMOI',
    link: 'https://imemoi.com',
    collections: [
      {
        main: ProductCategory.BAGS,
        handles: [
          'new-in',
          'imemoi-icons',
          'bags',
          'gabri-family',
          'teapot-family',
          'mini-bags',
          'bum-bags',
          'backpacks',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'accessories',
          'bag-charms',
          'phone-straps',
          'phone-cases',
          'key-holders',
          'card-holders',
        ],
      },
    ],
  },
  {
    id: 'demellier',
    name: 'Demellier',
    marketplace: 'DEMELLIER',
    link: 'https://demellierlondon.com',
    collections: [{ main: ProductCategory.BAGS, handles: ['all-bags'] }],
  },
  {
    id: 'aureumcollective',
    name: 'Aureumcollective',
    marketplace: 'AUREUMCOLLECTIVE',
    link: 'https://aureumcollective.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: ['new-arrivals', 'shop-all', 'hitting-the-archives'],
      },
      { main: ProductCategory.JEWELRY, handles: ['shop-all-jewelry'] },
    ],
  },
  {
    id: 'dehanche',
    name: 'Dehanche',
    marketplace: 'DEHANCHE',
    link: 'https://dehanche.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'shop-all',
          'new-arrivals',
          'seasonal-sale',
          'minimalist',
          'the-suede-collection',
          'western-edit',
          'exclusives',
          'mixed-metal',
          'exotic-prints',
          'best-sellers',
          'fall-collection',
          'pre-fall25-collection',
          'pre-spring-25',
          'the-terre-collection',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'sculptural-belts',
          'fluctuating-belts',
          '24-carat-gold-belts',
          'silver-belts',
          'soft-leather-belts',
        ],
      },
      { main: ProductCategory.JEWELRY, handles: ['jewelry'] },
    ],
  },
  {
    id: 'amanustudio',
    name: 'Amanustudio',
    marketplace: 'AMANUSTUDIO',
    link: 'https://amanustudio.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: ['best-sellers', 'the-fall-collection', 'shop-all'],
      },
      { main: ProductCategory.SHOES, handles: ['footwear'] },
      { main: ProductCategory.BAGS, handles: ['bags'] },
      { main: ProductCategory.ACCESSORIES, handles: ['belts-jewelry'] },
    ],
  },
  {
    id: 'b_lowthebelt',
    name: 'B Lowthebelt',
    marketplace: 'B_LOWTHEBELT',
    link: 'https://b-lowthebelt.com',
    collections: [
      { main: ProductCategory.BAGS, handles: ['bags'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'belts-new-arrivals',
          'belts-hip-belts-1',
          'belts-waist-belts',
          'belts-best-sellers',
        ],
      },
    ],
  },
  {
    id: 'jimmyfairly',
    name: 'Jimmyfairly',
    marketplace: 'JIMMYFAIRLY',
    link: 'https://www.jimmyfairly.com/en-us',
    collections: [
      { main: ProductCategory.BAGS, handles: ['tote-bags'] },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['women-sunglasses', 'women-eyeglasses', 'accessories'],
      },
    ],
  },
  {
    id: 'lespecs',
    name: 'Lespecs',
    marketplace: 'LESPECS',
    link: 'https://lespecs.com',
    collections: [
      { main: ProductCategory.ACCESSORIES, handles: ['shop-all-womens'] },
    ],
  },
  {
    id: 'jenniferbehr',
    name: 'Jenniferbehr',
    marketplace: 'JENNIFERBEHR',
    link: 'https://www.jenniferbehr.com',
    collections: [
      {
        main: ProductCategory.JEWELRY,
        handles: [
          'bridal-tiaras',
          'earrings',
          'tiaras-and-halos',
          'brooches',
          'bridal-necklaces',
          'bridal-earrings',
          'necklaces',
          'fine-jewelry',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'bridal-barrettes-1',
          'ponies',
          'bridal-combs',
          'bridal-voilettes-veils',
          'scarves',
          'headbands',
          'barrettes',
          'turbans',
          'voilettes',
          'bobby-pins',
          'hair-magnets',
          'bridal-bobby-pins',
          'bridal-headbands',
          'combs',
        ],
      },
    ],
  },
  {
    id: 'leletny',
    name: 'Leletny',
    marketplace: 'LELETNY',
    link: 'https://leletny.com',
    collections: [
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'ponycuffs',
          'bandanas',
          'barrettes',
          'bobbies',
          'the-bow-edit',
          'clips',
          'pins',
          'claw-clips',
          'crowns',
          'halos-1',
          'shop-combs',
          'shop-headbands',
          'headwraps',
          'scrunchies',
          'u-pins-1',
          'blusher-veils',
          'belts',
        ],
      },
      { main: ProductCategory.JEWELRY, handles: ['shop-jewelry'] },
    ],
  },
  {
    id: 'heavenmayhem',
    name: 'Heavenmayhem',
    marketplace: 'HEAVENMAYHEM',
    link: 'https://heavenmayhem.com',
    collections: [
      { main: ProductCategory.JEWELRY, handles: ['jewelry'] },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
    ],
  },
  {
    id: 'dorsey',
    name: 'Dorsey',
    marketplace: 'DORSEY',
    link: 'https://www.shopdorsey.com',
    collections: [
      {
        main: ProductCategory.JEWELRY,
        handles: [
          'the-riviere-collection',
          'custom-nav-necklaces',
          'custom-nav-earrings',
          'custom-nav-bracelets',
          'custom-nav-rings',
        ],
      },
    ],
  },
  {
    id: 'atpresent',
    name: 'Atpresent',
    marketplace: 'ATPRESENT',
    link: 'https://atpresent.com',
    collections: [
      {
        main: ProductCategory.JEWELRY,
        handles: [
          'earrings',
          'necklaces',
          'rings',
          'bracelets',
          'charms-pendants',
        ],
      },
    ],
  },
  {
    id: 'cultgaia',
    name: 'Cultgaia',
    marketplace: 'CULTGAIA',
    link: 'https://cultgaia.com',
    collections: [
      {
        main: ProductCategory.SHOES,
        handles: ['shoes', 'evening-shoes', 'sandals', 'boots', 'platforms'],
      },
      {
        main: ProductCategory.BAGS,
        handles: [
          'bags',
          'clutches',
          'shoulder-bags',
          'mini-bags',
          'crossbody-bags',
          'tote-bags',
        ],
      },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'clothing',
          'dresses',
          'gowns',
          'knits',
          'sets',
          'denim',
          'tops',
          'bottoms',
          'outerwear',
          'swim',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'jewelry',
          'earrings',
          'necklaces',
          'bracelets',
          'hair',
          'accessories',
          'belts',
          'sunglasses',
          'hats',
        ],
      },
    ],
  },
  {
    id: 'verafiedny',
    name: 'Verafiedny',
    marketplace: 'VERAFIEDNY',
    link: 'https://verafiedny.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: ['all-items', 'new-arrivals', 'ready-to-wear'],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['jewelry'] },
    ],
  },
  {
    id: 'porto_studio',
    name: 'Porto Studio',
    marketplace: 'PORTO_STUDIO',
    link: 'https://porto-studio.com',
    collections: [{ main: ProductCategory.BAGS, handles: ['the-pouch'] }],
  },
  {
    id: 'marialarosa',
    name: 'Marialarosa',
    marketplace: 'MARIALAROSA',
    link: 'https://www.marialarosa.it/en',
    collections: [
      { main: ProductCategory.BAGS, handles: ['bags'] },
      { main: ProductCategory.ACCESSORIES, handles: ['socks', 'accessories'] },
    ],
  },
  {
    id: 'ruedeverneuil',
    name: 'Ruedeverneuil',
    marketplace: 'RUEDEVERNEUIL',
    link: 'https://www.ruedeverneuil.com',
    collections: [
      { main: ProductCategory.CLOTHING, handles: ['collection'] },
      { main: ProductCategory.ACCESSORIES, handles: ['scarves', 'jewelry'] },
    ],
  },
  {
    id: 'merlettenyc',
    name: 'Merlettenyc',
    marketplace: 'MERLETTENYC',
    link: 'https://merlettenyc.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'all-ready-to-wear',
          'dresses',
          'tops-kimonos',
          'skirts-shorts',
          'shirts',
          'outerwear',
        ],
      },
      { main: ProductCategory.ACCESSORIES, handles: ['jewelry'] },
    ],
  },
  {
    id: 'ayllon',
    name: 'Ayllon',
    marketplace: 'AYLLON',
    link: 'https://ayllon.co',
    collections: [
      {
        main: ProductCategory.JEWELRY,
        handles: ['jewelry', 'rings', 'necklaces', 'bracelets'],
      },
      { main: ProductCategory.BAGS, handles: ['clutches'] },
      { main: ProductCategory.ACCESSORIES, handles: ['gift-cards'] },
    ],
  },
  {
    id: 'simonmillerusa',
    name: 'Simonmillerusa',
    marketplace: 'SIMONMILLERUSA',
    link: 'https://www.simonmillerusa.com',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'all-products',
          'new-arrivals',
          'ready-to-wear',
          'dresses',
          'tops',
          'knits',
          'bottoms',
          'outerwear',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['shoes'] },
      { main: ProductCategory.BAGS, handles: ['bags'] },
      { main: ProductCategory.ACCESSORIES, handles: ['accessories'] },
    ],
  },
  {
    id: 'maeden',
    name: 'Maeden',
    marketplace: 'MAEDEN',
    link: 'https://maeden.nl',
    collections: [
      {
        main: ProductCategory.BAGS,
        handles: [
          'bags',
          'structured',
          'shoulder',
          'crossbody',
          'tote',
          'mini',
          'leather',
          'canvas',
        ],
      },
    ],
  },
  {
    id: 'cliopeppiatt',
    name: 'Cliopeppiatt',
    marketplace: 'CLIOPEPPIATT',
    link: 'https://cliopeppiatt.co.uk',
    collections: [
      {
        main: ProductCategory.CLOTHING,
        handles: ['ready-to-wear', 'bridal', 'collection'],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['jewelry', 'accessories'],
      },
    ],
  },
  {
    id: 'ibeliv',
    name: 'Ibeliv',
    marketplace: 'IBELIV',
    link: 'https://it.ibeliv.fr',
    collections: [
      {
        main: ProductCategory.JEWELRY,
        handles: [
          'all',
          'new-arrivals',
          'bracelets',
          'necklaces',
          'rings',
          'earrings',
          'anklets',
        ],
      },
    ],
  },
  {
    id: 'lie_studio',
    name: 'Lie Studio',
    marketplace: 'LIE_STUDIO',
    link: 'https://lie-studio.com',
    collections: [
      {
        main: ProductCategory.JEWELRY,
        handles: [
          'jewelry',
          'earrings',
          'necklaces',
          'bracelets',
          'rings',
          'body-chains',
        ],
      },
      {
        main: ProductCategory.BAGS,
        handles: [
          'bags',
          'handbags',
          'crossbody',
          'clutches',
          'structured',
          'leather',
          'canvas',
        ],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: ['scarves', 'hair', 'belts', 'sunglasses', 'hats'],
      },
    ],
  },
  {
    id: 'eugeniakim',
    name: 'Eugeniakim',
    marketplace: 'EUGENIAKIM',
    link: 'https://eugeniakim.com',
    collections: [
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'hats',
          'timeless-collection',
          'packable-collection',
          'upf-hats',
          'ek-love',
          'personalized-sunhats',
          'bridal',
          'hair',
          'accessories',
        ],
      },
      { main: ProductCategory.BAGS, handles: ['bags-1'] },
    ],
  },
  {
    id: 'lackofcolor',
    name: 'Lackofcolor',
    marketplace: 'LACKOFCOLOR',
    link: 'https://lackofcolor.com',
    collections: [
      { main: ProductCategory.ACCESSORIES, handles: ['all-womens-hats'] },
    ],
  },
  {
    id: 'stetson',
    name: 'Stetson',
    marketplace: 'STETSON',
    link: 'https://stetson.com',
    collections: [
      {
        main: ProductCategory.JEWELRY,
        handles: ['womens-accessories-jewelry'],
      },
      {
        main: ProductCategory.ACCESSORIES,
        handles: [
          'hats',
          'womens-accessories-belts',
          'womens-accessories-wallets',
          'womens-accessories-fragrance',
        ],
      },
      { main: ProductCategory.SHOES, handles: ['boots-womens'] },
      {
        main: ProductCategory.CLOTHING,
        handles: [
          'womens-shirts',
          'womens-dresses',
          'womens-bottoms',
          'womens-outerwear',
        ],
      },
    ],
  },
  {
    id: 'italic',
    name: 'Italic',
    marketplace: 'ITALIC',
    link: 'https://cf29c4.myshopify.com',
    collections: [
      { main: ProductCategory.CLOTHING, handles: ['womens-clothing'] },
      { main: ProductCategory.JEWELRY, handles: ['jewelry-shop-all'] },
    ],
  },
];
