// Allocates a host port for every local service, starting from its default and
// walking upward until it finds one nothing else is listening on. Other projects
// on this machine routinely hold 5432/6379/27017/3000, so nothing may assume a
// fixed port.
//
// A port already published by one of our own running containers counts as
// available to us: re-running Tilt against a live stack keeps the same ports
// instead of shuffling everything one slot up.
//
// Prints the resolved environment as JSON on stdout (consumed by the Tiltfile)
// and writes .env.tilt, which docker compose reads for variable substitution.

import net from 'node:net'
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const SERVICES = [
  { name: 'postgres', env: 'POSTGRES_PORT', from: 5432, container: 'pandorlabs-postgres' },
  { name: 'mongodb', env: 'MONGODB_PORT', from: 27017, container: 'pandorlabs-mongodb' },
  { name: 'redis', env: 'REDIS_PORT', from: 6379, container: 'pandorlabs-redis' },
  { name: 'frontend', env: 'FRONTEND_PORT', from: 3000 },
  { name: 'backend', env: 'PORT', from: 3001 },
]

const MAX_PROBES = 100

/** Host ports our own containers currently publish, keyed by container name. */
function portsHeldByOurContainers() {
  const held = {}
  let output
  try {
    output = execFileSync(
      'docker',
      ['ps', '--filter', 'name=pandorlabs-', '--format', '{{.Names}}\t{{.Ports}}'],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] },
    )
  } catch {
    return held // Docker down or missing: every port simply looks foreign.
  }

  for (const line of output.trim().split('\n').filter(Boolean)) {
    const [name, ports = ''] = line.split('\t')
    // e.g. "0.0.0.0:5434->5432/tcp, [::]:5434->5432/tcp"
    const match = ports.match(/:(\d+)->/)
    if (match) held[name] = Number(match[1])
  }
  return held
}

function isFree(port) {
  return new Promise((resolve) => {
    const server = net.createServer()
    server.once('error', () => resolve(false))
    server.once('listening', () => server.close(() => resolve(true)))
    // 0.0.0.0 matches how Docker publishes, so this also catches a listener
    // bound only to a specific interface.
    server.listen(port, '0.0.0.0')
  })
}

async function allocate() {
  const held = portsHeldByOurContainers()
  const taken = new Set()
  const resolved = {}

  for (const service of SERVICES) {
    const ours = service.container ? held[service.container] : undefined
    if (ours && !taken.has(ours)) {
      resolved[service.name] = ours
      taken.add(ours)
      continue
    }

    let port = null
    for (let candidate = service.from; candidate < service.from + MAX_PROBES; candidate++) {
      if (taken.has(candidate)) continue
      if (await isFree(candidate)) {
        port = candidate
        break
      }
    }
    if (port === null) {
      throw new Error(
        `No free port for ${service.name} in ${service.from}-${service.from + MAX_PROBES - 1}.`,
      )
    }
    resolved[service.name] = port
    taken.add(port)
  }
  return resolved
}

const p = await allocate()

const env = {
  POSTGRES_PORT: String(p.postgres),
  MONGODB_PORT: String(p.mongodb),
  REDIS_PORT: String(p.redis),
  FRONTEND_PORT: String(p.frontend),
  PORT: String(p.backend),

  DATABASE_URL: `postgresql://postgres:postgres@localhost:${p.postgres}/pandorlabs`,
  MONGODB_URI: `mongodb://localhost:${p.mongodb}/pandorlabs`,
  REDIS_HOST: 'localhost',

  NEXT_PUBLIC_APP_URL: `http://localhost:${p.frontend}`,
  NEXT_PUBLIC_API_URL: `http://localhost:${p.backend}`,
  FRONTEND_URL: `http://localhost:${p.frontend}`,
}

const envFile = fileURLToPath(new URL('../.env.tilt', import.meta.url))
writeFileSync(
  envFile,
  '# Generated by scripts/tilt-ports.mjs on every `tilt up`. Do not edit.\n' +
    Object.entries(env)
      .map(([k, v]) => `${k}=${v}`)
      .join('\n') +
    '\n',
)

process.stdout.write(JSON.stringify(env))
